import re
from ibm_watsonx_orchestrate.agent_builder.tools import tool
from ibm_watsonx_orchestrate.agent_builder.tools.types import (
    PythonToolKind,
    PluginContext,
    AgentPostInvokePayload,
    AgentPostInvokeResult,
    TextContent,
    Message,
)

@tool(
    description="Adds a small grey AI‑generated disclaimer to the end of the agent's response.",
    kind=PythonToolKind.AGENTPOSTINVOKE,
)
def add_disclaimer_plugin(
    plugin_context: PluginContext,
    agent_post_invoke_payload: AgentPostInvokePayload,
) -> AgentPostInvokeResult:
    """
    Post‑invoke plug‑in that appends a disclaimer to the last text message
    returned by the agent.
    The disclaimer is rendered as small, grey text:
        <span style="font-size:0.8em; color:#777;">This message is generated by AI</span>
    Args:
        plugin_context (PluginContext): Context about the current run (not used here).
        agent_post_invoke_payload (AgentPostInvokePayload): The payload produced by the
            agent – contains a list of Message objects.
    Returns:
        AgentPostInvokeResult: Result containing the possibly‑modified payload and a
            flag indicating whether further processing should continue.
    """
    result = AgentPostInvokeResult()
    # ------------------------------------------------------------------
    # Guard‑clause – ensure we have a payload with at least one message
    # ------------------------------------------------------------------
    if (
        agent_post_invoke_payload is None
        or not agent_post_invoke_payload.messages
    ):
        # Nothing to modify – just continue
        result.continue_processing = True
        return result

    # ------------------------------------------------------------------
    # Work on the **last** message (the one the agent just produced)
    # ------------------------------------------------------------------
    last_msg: Message = agent_post_invoke_payload.messages[-1]

    # The plug‑in only knows how to handle plain‑text content.
    if not isinstance(last_msg.content, TextContent) or not last_msg.content.text:
        # If it isn’t a text message, leave it untouched.
        result.continue_processing = True
        return result

    # ------------------------------------------------------------------
    # Build the disclaimer HTML
    # ------------------------------------------------------------------
    disclaimer_html = (
        '<span style="font-size:0.8em; color:#777;">'
        "Message generated by AI"
        "</span>"
    )

    # If the existing text already ends with the disclaimer, don’t duplicate it.
    if not re.search(re.escape(disclaimer_html) + r"\s*$", last_msg.content.text):
        # Append a line break and the disclaimer.
        new_text = f"{last_msg.content.text.rstrip()}\n\n{disclaimer_html}"
    else:
        new_text = last_msg.content.text

    # ------------------------------------------------------------------
    # Create a new TextContent and Message instance with the updated text
    # ------------------------------------------------------------------
    new_content = TextContent(type="text", text=new_text)
    new_message = Message(role=last_msg.role, content=new_content)

    # ------------------------------------------------------------------
    # Produce a deep copy of the payload, replace the last message,
    # and return the result.
    # ------------------------------------------------------------------
    modified_payload = agent_post_invoke_payload.copy(deep=True)
    modified_payload.messages[-1] = new_message

    result.continue_processing = True
    result.modified_payload = modified_payload
    return result